#!/bin/bash

. /etc/cfncluster/cfnconfig

# Query instance metadata
instance_id_url="http://169.254.169.254/latest/meta-data/instance-id"
availability_zone_url="http://169.254.169.254/latest/meta-data/placement/availability-zone/"

instance_id=$(curl --retry 3 --retry-delay 0 --silent --fail ${instance_id_url})
availability_zone=$(curl --retry 3 --retry-delay 0 --silent --fail ${availability_zone_url})

# Notify compute is ready
aws --region ${cfn_region} sqs send-message --queue-url ${cfn_sqs_queue} --message-body '{"Type" : "Notification", "Message" : "{\"StatusCode\":\"Complete\",\"Description\":\"Succesfully launched '${instance_id}'\",\"Event\":\"cfncluster:COMPUTE_READY\",\"EC2InstanceId\":\"'${instance_id}'\",\"Slots\":\"'${cfn_instance_slots}'\"}"}'